name: Deploy React + Vite to Github Pages

on: 
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-deplay:
    runs-on: ubuntu-latest

    steps:
      # checkout the repository
      - name: Checkout code
        uses: actions/checkout@v6

      #Set up Nodejs
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24.11.1

      #Install Dependencies
      - name: Install Dependencies
        run: npm install 

      #Build the project
      - name: Build Project
        run: npm run build

      #Deploy to github pages
      - name: Deploy to github pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist